# Generated by Django 4.0.6 on 2022-07-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVE',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('last_update', models.DateField()),
                ('version', models.CharField(max_length=7)),
                ('cvss_score', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('sector', models.CharField(max_length=128)),
                ('cve_ids', models.ManyToManyField(to='home.cve')),
                ('products', models.ManyToManyField(to='home.product')),
            ],
        ),
    ]
